version: "3.7"

services:
  web:
    container_name: cmpt-470-project-flask-container
    image: cmpt-470-project-flask
    build:
      context: .
      dockerfile: Dockerfile.flask
    env_file:
      - .env
  db:
    container_name: cmpt-470-project-db-container
    image: 'postgres:14.0-alpine3.14'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  client:
    container_name: cmpt-470-project-react-app-container
    image: cmpt-470-project-react-app
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - './client:/app'
  proxy:
    container_name: cmpt-470-project-proxy
    image: cmpt-470-project-proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 8080:80

volumes:
  db:
